# Generated by Django 2.0.2 on 2019-10-26 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='paradigm',
            new_name='Password',
        ),
    ]
